
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package flex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 30;
  public static final int OP_MENIG = 13;
  public static final int OP_MAYIG = 14;
  public static final int BEGINPROGRAM = 33;
  public static final int COR_CIE = 23;
  public static final int INT = 3;
  public static final int OP_DIV = 19;
  public static final int PAR_ABRE = 24;
  public static final int AND = 20;
  public static final int OP_DIS = 15;
  public static final int IGUAL = 9;
  public static final int COR_ABRE = 22;
  public static final int OR = 21;
  public static final int MIENTRAS = 35;
  public static final int ENDPROGRAM = 34;
  public static final int LLAV_ABRE = 26;
  public static final int OP_MUL = 18;
  public static final int CONST_FLOAT = 8;
  public static final int IF = 36;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int ENDDECLARE = 32;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int OP_MEN = 12;
  public static final int DECLARE = 31;
  public static final int ELSE = 37;
  public static final int OP_IGUAL = 11;
  public static final int DEFAULT = 40;
  public static final int LET = 39;
  public static final int FLOAT = 4;
  public static final int OP_MAY = 10;
  public static final int CONST_STRING = 6;
  public static final int LLAV_CIE = 27;
  public static final int DOSPUN_IG = 28;
  public static final int STRING = 5;
  public static final int OP_SUMA = 16;
  public static final int PRINT = 38;
  public static final int PAR_CIE = 25;
  public static final int CONST_INT = 7;
  public static final int OP_RES = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INT",
  "FLOAT",
  "STRING",
  "CONST_STRING",
  "CONST_INT",
  "CONST_FLOAT",
  "IGUAL",
  "OP_MAY",
  "OP_IGUAL",
  "OP_MEN",
  "OP_MENIG",
  "OP_MAYIG",
  "OP_DIS",
  "OP_SUMA",
  "OP_RES",
  "OP_MUL",
  "OP_DIV",
  "AND",
  "OR",
  "COR_ABRE",
  "COR_CIE",
  "PAR_ABRE",
  "PAR_CIE",
  "LLAV_ABRE",
  "LLAV_CIE",
  "DOSPUN_IG",
  "COMA",
  "DOSPUNTOS",
  "DECLARE",
  "ENDDECLARE",
  "BEGINPROGRAM",
  "ENDPROGRAM",
  "MIENTRAS",
  "IF",
  "ELSE",
  "PRINT",
  "LET",
  "DEFAULT"
  };
}

