
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pruebaast;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int palabraavg = 14;
  public static final int cte = 18;
  public static final int corcheteC = 13;
  public static final int corcheteA = 12;
  public static final int coma = 15;
  public static final int por = 6;
  public static final int eol = 4;
  public static final int menos = 3;
  public static final int llaveC = 10;
  public static final int EOF = 0;
  public static final int dividido = 5;
  public static final int llaveA = 9;
  public static final int id = 16;
  public static final int error = 1;
  public static final int asigna = 11;
  public static final int constString = 17;
  public static final int parentesisC = 8;
  public static final int mas = 2;
  public static final int parentesisA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "eol",
  "dividido",
  "por",
  "parentesisA",
  "parentesisC",
  "llaveA",
  "llaveC",
  "asigna",
  "corcheteA",
  "corcheteC",
  "palabraavg",
  "coma",
  "id",
  "constString",
  "cte"
  };
}

